---
version: "2"
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      extensions:
      - .vue
  eslint:
    enabled: true
    channel: "eslint-4"
      extensions:
      - .vue
      - .js
  fixme:
    enabled: true
ratings:
  paths:
  - "./**/*.vue"
exclude_paths:
- dist/
- .nuxt/
- node_modules/
