---
version: "2"
plugins:
  eslint:
    enabled: true
    config:
      extensions:
      - .vue
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
exclude_patterns:
- dist/
- .nuxt/
- node_modules/
