# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: cimg/node:16.15.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install node_modules
          command: |
            if [ ! -e node_modules ]; then
              yarn install
            fi
      - run: yarn lint

  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:16.15.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo
    environment:
      - NODE_ENV: production
    steps:
      - checkout

      - run:
          name: install node_modules
          command: |
            if [ ! -e node_modules ]; then
              yarn install
            fi

      - run: echo $SlackTOKEN > .env

      - run: yarn build

  deploy:
    docker:
      - image: cimg/node:16.15.1
    environment:
      - NODE_ENV: production
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: git config user.name $GITHUB_NAME
      - run: git config user.email $GITHUB_EMAIL
      - run:
          name: Deploy gh-pages
          command: |
            yarn && \
            echo $SlackTOKEN > .env && \
            yarn generate && \
            yarn deploy:gh-pages && \
            curl -X POST -d {} https://api.netlify.com/build_hooks/5cc93fb77d8bfbb0cf910b05

workflows:
  version: 2
  test-build:
    jobs:
      - test
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 1,10 * * *"
          filters:
            branches:
              only: main
    jobs:
      - deploy
